FROM seldonio/pyseldon:%SELDON_PYTHON_PACKAGE_VERSION%

ENV SELDON_HOME=/home/seldon
COPY deep_mnist_pipeline $SELDON_HOME/deep_mnist_pipeline

RUN conda install -y -c conda-forge tensorflow

COPY run_microservice.sh /run_microservice.sh

CMD ["/run_microservice.sh"]