# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iris.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iris.proto',
  package='io.seldon.microservice.iris',
  syntax='proto3',
  serialized_pb=_b('\n\niris.proto\x12\x1bio.seldon.microservice.iris\"D\n\x12IrisPredictRequest\x12\n\n\x02\x66\x31\x18\x01 \x01(\x02\x12\n\n\x02\x66\x32\x18\x02 \x01(\x02\x12\n\n\x02\x66\x33\x18\x03 \x01(\x02\x12\n\n\x02\x66\x34\x18\x04 \x01(\x02\x42/\n\x1bio.seldon.microservice.irisB\x0eIrisClassifierP\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IRISPREDICTREQUEST = _descriptor.Descriptor(
  name='IrisPredictRequest',
  full_name='io.seldon.microservice.iris.IrisPredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f1', full_name='io.seldon.microservice.iris.IrisPredictRequest.f1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f2', full_name='io.seldon.microservice.iris.IrisPredictRequest.f2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f3', full_name='io.seldon.microservice.iris.IrisPredictRequest.f3', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f4', full_name='io.seldon.microservice.iris.IrisPredictRequest.f4', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['IrisPredictRequest'] = _IRISPREDICTREQUEST

IrisPredictRequest = _reflection.GeneratedProtocolMessageType('IrisPredictRequest', (_message.Message,), dict(
  DESCRIPTOR = _IRISPREDICTREQUEST,
  __module__ = 'iris_pb2'
  # @@protoc_insertion_point(class_scope:io.seldon.microservice.iris.IrisPredictRequest)
  ))
_sym_db.RegisterMessage(IrisPredictRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.seldon.microservice.irisB\016IrisClassifierP\001'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
