FROM seldonio/pyseldon:%SELDON_PYTHON_PACKAGE_VERSION%

ENV SELDON_HOME=/home/seldon
# COPY deep_mnist_pipeline $SELDON_HOME/deep_mnist_pipeline
COPY create_pipeline.py $SELDON_HOME/create_pipeline.py

# RUN conda install -y -c conda-forge tensorflow

COPY train_model.sh $SELDON_HOME/train_model.sh
COPY run_microservice.sh /run_microservice.sh

# CMD ["/run_microservice.sh"]

CMD ["bash"]